// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRX8U8ZdxBcV08Xn4mZnjlwuMZeKeAx4k',
    appId: '1:706345535050:web:5761c5290184073da6c8b3',
    messagingSenderId: '706345535050',
    projectId: 'jadin-pameran',
    authDomain: 'jadin-pameran.firebaseapp.com',
    storageBucket: 'jadin-pameran.appspot.com',
    measurementId: 'G-P3ZSDXLNVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2i8ngZyNf30AZMzl0N0Y8lf6BlajpAtM',
    appId: '1:706345535050:android:5798debff2e9010fa6c8b3',
    messagingSenderId: '706345535050',
    projectId: 'jadin-pameran',
    storageBucket: 'jadin-pameran.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyhubjcMwaKEK8FkjccinjlyE-wUJ_bzE',
    appId: '1:706345535050:ios:5ad6d8094f4181a8a6c8b3',
    messagingSenderId: '706345535050',
    projectId: 'jadin-pameran',
    storageBucket: 'jadin-pameran.appspot.com',
    iosClientId: '706345535050-bhiviio7re4e6uj0m0q2mmvi935l4tm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.jadinPameran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyhubjcMwaKEK8FkjccinjlyE-wUJ_bzE',
    appId: '1:706345535050:ios:5ad6d8094f4181a8a6c8b3',
    messagingSenderId: '706345535050',
    projectId: 'jadin-pameran',
    storageBucket: 'jadin-pameran.appspot.com',
    iosClientId: '706345535050-bhiviio7re4e6uj0m0q2mmvi935l4tm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.jadinPameran',
  );
}
